server:
  port: 8082

spring:
    application:
        name: public-api

services:
  user:
    base-url: http://localhost:8081
  property:
    base-url: http://localhost:6001

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG