server:
  port: 8081

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

logging:
  level:
    '[com.aziz.users.users]': INFO
    '[org.hibernate.SQL]': INFO